###

GET http://localhost:8080/index.html
Host: localhost
### Returns index.html
### TextFile

HEAD http://localhost:8080/index.html
Host: localhost
### Returns just the header  without sending the actual document.

### Funkar inte just nu
POST http://localhost:8080/action_page.html
Host: localhost

###